[package]
name = "sbrs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "*"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
